/**
 * Mock data for development
 */

export const mockBeaches = [
  {
    id: '1',
    name: 'Praia do Sancho',
    city: 'Fernando de Noronha',
    state: 'PE',
    region: 'Nordeste',
    latitude: -3.8456,
    longitude: -32.4177,
    description: 'Considerada uma das praias mais bonitas do mundo, com falésias e águas cristalinas.',
    imageUrl: 'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=500&h=400&fit=crop',
    rating: 4.9,
    waveHeight: '0.8m',
    waterTemp: '28°C',
    surfQuality: 'Moderado',
    hasInfrastructure: true,
    hasSurfSchools: false,
    hasRestaurants: true,
    hasParking: true,
    bestSeason: 'Set - Mar',
  },
  {
    id: '2',
    name: 'Praia de Lopes Mendes',
    city: 'Angra dos Reis',
    state: 'RJ',
    region: 'Sudeste',
    latitude: -23.1234,
    longitude: -44.5678,
    description: 'Três quilômetros de areia branca em ilha Grande com ondas perfeitas para bodyboard.',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500&h=400&fit=crop',
    rating: 4.8,
    waveHeight: '0.8-1.5m',
    waterTemp: '25°C',
    surfQuality: 'Bom',
    hasInfrastructure: true,
    hasSurfSchools: true,
    hasRestaurants: true,
    hasParking: false,
    bestSeason: 'Set - Mar',
  },
  {
    id: '3',
    name: 'Baía dos Golfinhos',
    city: 'Praia',
    state: 'RN',
    region: 'Nordeste',
    latitude: -5.8267,
    longitude: -35.2075,
    description: 'Piscinas naturais cercadas por falésias com golfinhos rotadores visitando diariamente.',
    imageUrl: 'https://images.unsplash.com/photo-1472933187732-9d4017ed6ab3?w=500&h=400&fit=crop',
    rating: 4.7,
    waveHeight: '0.3-0.8m',
    waterTemp: '29°C',
    surfQuality: 'Iniciante',
    hasInfrastructure: true,
    hasSurfSchools: false,
    hasRestaurants: false,
    hasParking: true,
    bestSeason: 'Set - Mar',
  },
  {
    id: '4',
    name: 'Praia do Espelho',
    city: 'Caraíva',
    state: 'BA',
    region: 'Nordeste',
    latitude: -16.8297,
    longitude: -39.1031,
    description: 'Falésias coloridas e piscinas naturais com águas transparentes que refletem o céu.',
    imageUrl: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=500&h=400&fit=crop',
    rating: 4.9,
    waveHeight: '0.5-1.2m',
    waterTemp: '27°C',
    surfQuality: 'Moderado',
    hasInfrastructure: false,
    hasSurfSchools: false,
    hasRestaurants: true,
    hasParking: false,
    bestSeason: 'Abr - Set',
  },
  {
    id: '5',
    name: 'Praia de Copacabana',
    city: 'Rio de Janeiro',
    state: 'RJ',
    region: 'Sudeste',
    latitude: -23.0255,
    longitude: -43.1821,
    description: 'Icônica praia urbana com infraestrutura completa e movimento o ano todo.',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500&h=400&fit=crop',
    rating: 4.5,
    waveHeight: '1.0-2.0m',
    waterTemp: '24°C',
    surfQuality: 'Bom',
    hasInfrastructure: true,
    hasSurfSchools: true,
    hasRestaurants: true,
    hasParking: true,
    bestSeason: 'Ano todo',
  },
  {
    id: '6',
    name: 'Praia de Pipoca',
    city: 'Ceará',
    state: 'CE',
    region: 'Nordeste',
    latitude: -4.2598,
    longitude: -38.6819,
    description: 'Praia selvagem e pouco explorada com dunas e piscinas naturais.',
    imageUrl: 'https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=500&h=400&fit=crop',
    rating: 4.6,
    waveHeight: '1.5-2.5m',
    waterTemp: '30°C',
    surfQuality: 'Avançado',
    hasInfrastructure: false,
    hasSurfSchools: false,
    hasRestaurants: false,
    hasParking: true,
    bestSeason: 'Jun - Ago',
  },
];

export const mockConditions: Record<string, any> = {
  '1': {
    timestamp: new Date().toISOString(),
    waveHeight: 0.3,
    temperature: 27,
    windSpeed: 8,
    weatherDescription: 'Ensolarado',
    swellHeight: 0.5,
    waveDirection: 110,
    wavePeriod: 7,
    aiReview: {
      text: 'Condições paradisíacas para relaxamento e contemplação. Piscinas naturais formadas entre os recifes oferecem banho seguro e águas transparentes que refletem o céu.',
      bestTime: '09:00 - 16:00',
      ratings: {
        surf: 1.5,
        swim: 9.0,
        fishing: 4.5,
      },
      recommendations: ['Piscinas naturais cristalinas', 'Falésias coloridas para fotos', 'Mar calmo o dia todo'],
      warnings: ['Acesso por estrada de terra', 'Poucos pontos de sombra na praia'],
    },
  },
  '2': {
    timestamp: new Date().toISOString(),
    waveHeight: 0.8,
    temperature: 25,
    windSpeed: 12,
    weatherDescription: 'Parcialmente Nublado',
    swellHeight: 1.2,
    waveDirection: 95,
    wavePeriod: 8,
    aiReview: {
      text: 'Três quilômetros de areia branca em ilha Grande com ondas perfeitas para bodyboard.',
      bestTime: '06:00 - 18:00',
      ratings: {
        surf: 8.0,
        swim: 6.0,
        fishing: 8.0,
      },
      recommendations: ['Ondas formadas e consistentes', 'Pouca multidão', 'Boa para intermediários'],
      warnings: ['Corrente lateral ao norte', 'Poucos pontos de sombra na praia'],
    },
  },
};
